### ISSUE TITLE
Why the minSdkVersion is 19 when App Shortcuts is available from API level 25 or higher?

### ISSUE THREAD

**Issue by Amejia481** [AOrobator/Konstellations#1]
I noticed some warnings of API level uses higher than the minimum SDK level that could cause the app to crash if it is used on API levels lower than 25.

Would you mind if I send a pull request updating the minimum SDK level to 25?

**Comment by AOrobator** [comment]
The app shouldn't crash because there are API level checks. If you notice a crash on a lower API level, you can file a bug for that.
